version: '3'
services:
    apache:
        build: .docker/apache
        container_name: drive_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf4
        depends_on:
          - php

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --sql_mode=""
        container_name: drive_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4
        ports:
            - 3307:3306

    php:
        build: .docker/php
        container_name: drive_php
        volumes:
          - .:/home/wwwroot/sf4
        environment:
          - maildev_host=drive_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: drive_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8091:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: drive_maildev
        ports:
          - 8001:80
